skip-missing: true
ignores:
  # deps
  - bootstrap
  - bootswatch
  - typeface-open-sans
  - prettier
  - "@types/jest"
  - "@types/node"
  # devDeps
  - "@commitlint/travis-cli"
  - "@storybook/preset-create-react-app"
  - depcheck
  - markdownlint-cli
